#!/bin/bash

COMMAND=$1

if [ "$COMMAND" = "r" ]
then
    cd rstuff && Rscript script.R
elif [ "$COMMAND" = "node" ]
then
    node nodestuff/test.js
elif [ "$COMMAND" = "setup" ]
then
    cd rstuff
    Rscript -e "renv::restore()"
    cd ../nodestuff
    npm install
fi
