name: Build and deploy
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  test-node-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node dependencies
        working-directory: ./nodestuff
        run: npm install
      - name: Run the command
        run: node ./nodestuff/test.js
  test-r-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install R
        run: sudo apt-get update && sudo apt-get install -y r-base
      - name: Install microbenchmark
        working-directory: ./rstuff
        run: sudo Rscript -e "renv::restore()"
      - name: Run the script
        working-directory: ./rstuff
        run: sudo Rscript script.R
  test-website-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.10' 
      - name: Install mkdocs
        run: pip install mkdocs
      - name: Build the website with --strict
        working-directory: ./website
        run: mkdocs build --strict
  deploy-website:
    needs: test-website-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - name: Publish site to GH Pages
        working-directory: ./website
        run: mkdocs gh-deploy --force
