on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test
jobs:
  node-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install node dependencies
        working-directory: ./nodestuff
        run: npm install
      - name: Run the command
        run: node ./nodestuff/test.js
