on:
  pull_request:
    branches:
      - master

name: test-rstuff
jobs:
  r-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install R
        run: sudo apt-get update && sudo apt-get install -y r-base
      - name: Install microbenchmark
        working-directory: ./rstuff
        run: sudo Rscript -e "renv::restore()"
      - name: Run the script
        working-directory: ./rstuff
        run: sudo Rscript script.R
