on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test
jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.10' 
      - name: Install mkdocs
        run: pip install mkdocs
      - name: Build the website with --strict
        working-directory: ./website
        run: mkdocs build --strict
